# Generated by Django 6.0.5 on 2026-06-22 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('titulo', '0002_alter_titulo_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(help_text='Id do instrutor', primary_key=True, serialize=False)),
                ('rg', models.CharField(help_text='Informe o RG do instrutor', max_length=15)),
                ('nome', models.CharField(help_text='Informe o nome do Instrutor', max_length=70)),
                ('data_nascimento', models.DateField(blank=True, help_text='Informe a data de nascimento do instrutor', null=True)),
                ('ddd', models.CharField(help_text='Informe o DDD do instrutor', max_length=3)),
                ('telefone', models.CharField(help_text='Informe o telefone do instrutor', max_length=9)),
                ('codigo_titulo', models.ForeignKey(blank=True, db_column='codigo_titulo', help_text='Informe o código do título do instrutor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos', to='titulo.titulo')),
            ],
        ),
    ]
