# Generated by Django 6.0.5 on 2026-07-09 00:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0002_alter_aluno_data_saida_alter_aluno_nome'),
        ('instrutor', '0001_initial'),
        ('tipodeatividade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('numero', models.AutoField(help_text='Informe o número da Turma', primary_key=True, serialize=False)),
                ('horario_aula', models.TimeField(help_text='Informe a hora de aula da Turma')),
                ('duracao_aula', models.SmallIntegerField(default=4, help_text='Informe a duração da aula da Turma')),
                ('data_inicial', models.DateField(default=django.utils.timezone.now, help_text='Informe a data inicial da Turma')),
                ('data_final', models.DateField(blank=True, help_text='Informe a data final da Turma', null=True)),
                ('codigo_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='tipodeatividade.tipodeatividade')),
                ('id_instrutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrutores', to='instrutor.instrutor')),
                ('matricula_monitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='aluno.aluno')),
            ],
        ),
    ]
