# Generated by Django 6.0.5 on 2026-06-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_matricula', models.DateField()),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('monitor', models.BooleanField(default=False)),
            ],
        ),
    ]
