# Generated by Django 6.0.5 on 2026-07-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_saida',
            field=models.DateField(blank=True, help_text='Informe a data final de matrícula do aluno', null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(help_text='Informe o nome do aluno', max_length=100),
        ),
    ]
