# Generated by Django 6.0.5 on 2026-06-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('codigo', models.AutoField(help_text='código do Título', primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Informe a descrição do Título', max_length=70)),
            ],
        ),
    ]
