# Generated by Django 6.0.5 on 2026-06-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipodeatividade',
            fields=[
                ('codigo', models.AutoField(help_text='código de Tipos de Atividade', primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Informe a descrição do tipo de atividade', max_length=70)),
            ],
        ),
    ]
